"""
ExportCADUCS — Generate CAD coordinate setup files from stored project coordinates.

Outputs to C:\BIM_Automation\data\output\:
  autocad_setup.scr         — Runnable AutoCAD / Plant3D / CADWorx script
  revit_coord_setup.txt     — Human-readable Revit manual setup instructions
  coordinate_report.txt     — Full project coordinate summary

Requires CoordinateSetup to have been run first. No model changes.
"""
import traceback
import os
from datetime import date

from pyrevit import revit, script
from bim_utils import OUTPUT_DIR
from coord_utils import load_coords

doc    = revit.doc
output = script.get_output()


def write_autocad_script(coords, path):
    content = (
        "; AutoCAD / Plant3D / CADWorx coordinate setup script\n"
        "; Generated by BIMTools ExportCADUCS — {date}\n"
        "; Run in AutoCAD: type SCRIPT and select this file\n"
        "\n"
        "UCS\nW\n"
        "UCS\nOrigin\n"
        "{e},{n},{z}\n"
        "UCS\nZ\n"
        "{rot}\n"
        "PLAN\nC\n"
    ).format(
        date=date.today().isoformat(),
        e=round(coords["easting"],      3),
        n=round(coords["northing"],     3),
        z=round(coords["elevation"],    3),
        rot=round(coords["rotation_deg"], 4),
    )
    with open(path, "w") as f:
        f.write(content)


def write_revit_setup(coords, path):
    content = (
        "REVIT COORDINATE SETUP INSTRUCTIONS\n"
        "Generated: {date}\n"
        "Reference Grid: {grid}\n"
        "{sep}\n\n"
        "1. Open Manage > Project Location > Specify Coordinates at a Point\n"
        "   OR manually move the Survey Point (unclip it first):\n\n"
        "   Survey Point\n"
        "   E (X):  {e:.3f} ft\n"
        "   N (Y):  {n:.3f} ft\n"
        "   Elev:   {z:.3f} ft\n\n"
        "2. Project Base Point: set to 0, 0, 0\n\n"
        "3. True North:\n"
        "   Manage > Project Location > Position > Rotate True North\n"
        "   Angle from Project North to True North: {rot:.4f} degrees\n\n"
        "4. Clip the Survey Point after setup.\n"
    ).format(
        date=date.today().isoformat(),
        grid=coords["ref_grid"],
        sep="=" * 50,
        e=coords["easting"],
        n=coords["northing"],
        z=coords["elevation"],
        rot=coords["rotation_deg"],
    )
    with open(path, "w") as f:
        f.write(content)


def write_coord_report(coords, path):
    content = (
        "PROJECT COORDINATE REPORT\n"
        "Generated: {date}\n"
        "{sep}\n\n"
        "Reference Grid:    {grid}\n\n"
        "Survey Coordinates\n"
        "  Easting:         {e:.3f}\n"
        "  Northing:        {n:.3f}\n"
        "  Elevation:       {z:.3f} ft\n\n"
        "Project North Rotation\n"
        "  True North:      {rot:.4f} degrees\n\n"
        "Revit Setup\n"
        "  Survey Point =   {e:.3f}, {n:.3f}, {z:.3f}\n"
        "  Project Base Point = 0, 0, 0\n\n"
        "CAD Setup\n"
        "  UCS Origin =     {e:.3f}, {n:.3f}, {z:.3f}\n"
        "  UCS Rotation =   {rot:.4f} degrees\n"
    ).format(
        date=date.today().isoformat(),
        sep="=" * 50,
        grid=coords["ref_grid"],
        e=coords["easting"],
        n=coords["northing"],
        z=coords["elevation"],
        rot=coords["rotation_deg"],
    )
    with open(path, "w") as f:
        f.write(content)


def run():
    coords = load_coords(doc)
    if coords is None:
        output.print_md(
            "**No coordinate data found.**\n"
            "Run **CoordinateSetup** first."
        )
        return

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    scr_path    = os.path.join(OUTPUT_DIR, "autocad_setup.scr")
    revit_path  = os.path.join(OUTPUT_DIR, "revit_coord_setup.txt")
    report_path = os.path.join(OUTPUT_DIR, "coordinate_report.txt")

    write_autocad_script(coords, scr_path)
    write_revit_setup(coords,    revit_path)
    write_coord_report(coords,   report_path)

    output.print_md("## CAD Coordinate Package Exported\n")
    output.print_md(
        "| File | Path |\n|---|---|\n"
        "| AutoCAD script | `{}` |\n"
        "| Revit setup guide | `{}` |\n"
        "| Coordinate report | `{}` |".format(scr_path, revit_path, report_path)
    )
    output.print_md(
        "\n**AutoCAD / Plant3D / CADWorx:** type `SCRIPT` and select `autocad_setup.scr`"
    )


try:
    run()
except Exception:
    output.print_md("**Error in ExportCADUCS:**")
    output.print_md("```\n{}\n```".format(traceback.format_exc()))
