#!/usr/bin/env python3
"""Generate missing Starter Plan lesson files for Days 68-90 across all disciplines."""
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from backend.core.paths import STARTER_PLAN_DIR  # noqa: E402

BASE = STARTER_PLAN_DIR / "messages"
SCOPE = "\nScope note:\nThis is general educational content, not project review, engineering verification, code compliance confirmation, or construction approval."

def w(disc, day, title, matters, concept_lines, lens, checks, mistake, action):
    path = BASE / disc / f"day_{day:03d}.txt"
    if path.exists():
        print(f"  skip {disc}/day_{day:03d} (exists)")
        return
    concept = "\n".join(f"- {c}" for c in concept_lines)
    ck = "\n".join(f"- Check: {c}" for c in checks)
    content = (
        f"LUA BIM LABS Starter\nDay {day} - {title}\n\n"
        f"1. Why This Matters\n{matters}\n\n"
        f"2. Core Concept\n{concept}\n\n"
        f"3. Real Project Lens\n{lens}\n\n"
        f"4. BIM Check\n{ck}\n\n"
        f"5. Common Mistake\n{mistake}\n\n"
        f"6. Today's Action\n{action}"
        f"{SCOPE}"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  ✅ {disc}/day_{day:03d}")

# ─────────────────────────────────────────────
# HVAC  Days 72-90
# ─────────────────────────────────────────────
w("hvac",72,"Condensate Drain Piping — Slope and Connection",
"Condensate drainage is one of the most overlooked HVAC coordination issues. A poorly modeled drain pan connection or missing slope causes pooling, overflow, and water damage — all avoidable with correct BIM coordination.",
["Every FCU, AHU, and chilled beam produces condensate that must drain by gravity to the nearest sanitary stack",
 "The condensate drain pipe must slope continuously — minimum 1:50 — from the equipment outlet to the stack",
 "In Revit: connect the FCU drain connector to a sloped pipe routed to the plumbing stack",
 "Coordination check: does the drain route conflict with ductwork or cable tray below the ceiling void?",
 "Drain pan invert level must be at the correct height — not connected symbolically at the same elevation as the outlet"],
"On a hotel project, 14 FCU condensate drains were modeled horizontally with no slope. The plumbing engineer flagged the error before the model was issued. Re-routing with correct slope added 120mm of vertical drop per connection — a small change that would have caused ceiling water damage if undetected.",
["the condensate drain pipe has a continuous downward slope from FCU outlet to the sanitary stack",
 "no ductwork or cable tray blocks the drain pipe route below the FCU",
 "the FCU Revit family has a drain connector at the correct height relative to the drain pan"],
"Beginners connect condensate drains at the same elevation as the FCU outlet, treating it as a flat pipe rather than a sloped gravity drain.",
"Sketch the condensate path for one FCU: start point (drain pan), slope direction, and discharge point to the plumbing stack.")

w("hvac",73,"Fire Dampers — Placement Rules and BIM Modeling",
"Fire dampers are required wherever HVAC ducts penetrate fire-rated walls and floors. Missing dampers in the BIM model are only discovered during fire authority approval — causing delays that are entirely avoidable.",
["A fire damper installed in the duct at a fire-rated wall closes automatically under heat to prevent fire spreading through the duct",
 "Combination fire/smoke dampers are required in smoke-control zone boundaries",
 "In Revit: place the fire damper accessory family at the face of the fire-rated wall, not in the middle of the duct run",
 "Coordination with architecture: fire ratings of all walls must be confirmed before damper placement",
 "Access requirement: a maintenance access panel must be provided downstream of every fire damper for inspection and reset"],
"On a hospital project, the fire consultant identified 23 fire-rated wall penetrations without fire dampers in the federated model. The HVAC modeler had routed ducts through the walls without placing damper families because the architectural model had not yet flagged the fire ratings. Resolving this delayed the fire authority submission by two weeks.",
["every duct crossing a fire-rated wall or floor has a fire damper placed at the face of the rated element",
 "each fire damper has clearance for an access panel on the accessible side",
 "the fire rating of all wall penetrations is confirmed in the architectural model before dampers are placed"],
"Beginners route ducts through rated walls and mark fire dampers as 'TBC' without placing the family. This creates gaps only discovered during authority review.",
"Identify one fire-rated wall in any model or drawing. Count how many ducts pass through it and note how many would require a fire damper.")

w("hvac",74,"AHU and Mechanical Room Layout Coordination",
"Mechanical rooms contain the largest HVAC equipment on a project. Getting the room layout right in BIM before construction saves rework, crane costs, and structural changes that become very expensive after concrete is poured.",
["AHU room coordination involves: equipment footprint and height, maintenance clearances, vibration isolation bases, pipe connection directions, air intake and discharge routes",
 "Clearances: AHU typically requires 1000mm filter-access clearance on the filter face, 600mm minimum on other sides",
 "Structural coordination: AHU bases often require reinforced pad footings or spring isolator systems in the structural model",
 "Pipe connections to AHU: chilled water supply and return, condensate drain, hot water — routed to the correct connection face without blocking access",
 "Lift route: for equipment replacement, verify there is a lift path from the AHU to the building exterior"],
"On a commercial tower, the mechanical room layout was issued without verifying lift access for AHU replacement. After construction, the facilities team discovered the AHU could not be removed without demolishing a partition wall. A $40,000 modification was required — a cost that BIM coordination would have caught before a single brick was laid.",
["the AHU has manufacturer-specified maintenance clearance on all sides",
 "chilled water pipe connections are on the correct AHU face and accessible without stepping over other equipment",
 "there is a clear lift route from the mechanical room entrance to the AHU location"],
"Beginners model the AHU correctly but forget the maintenance clearance zone. Placing equipment too close together looks fine on screen but fails in practice.",
"For one piece of HVAC equipment, find its manufacturer's minimum clearance requirements and verify whether those clearances exist in the model or sketch.")

w("hvac",75,"VAV Box Placement and Ceiling Zone Coordination",
"VAV boxes occupy ceiling voids and serve specific zones. Getting their placement wrong causes duct rerouting, ceiling conflicts, and poor acoustic performance — all discovered too late if BIM coordination is skipped.",
["A VAV box receives primary air from the AHU supply duct and delivers conditioned air to its zone through downstream ductwork",
 "Placement factors: VAV box must be accessible via ceiling access panel below, must not conflict with structural beams, and must have space for downstream connections",
 "The primary supply duct (AHU to VAV) is high-velocity and requires more clearance than downstream branch ducts",
 "In Revit: the VAV box family has supply air inlet and outlet connectors — assign both to the correct system",
 "Coordination sequence: route the primary duct first, then position VAV boxes along the duct at zone boundaries"],
"On a large office floor with a 500mm ceiling void, VAV boxes were placed for coordination convenience without reference to the structural beam layout. Three VAV boxes conflicted with primary beams. Resolving the conflicts required reducing the zone count from 18 to 14 and re-routing two primary supply ducts.",
["each VAV box has a ceiling access panel directly below it in the reflected ceiling plan",
 "the primary supply duct from AHU to VAV box does not conflict with structural beams or main cable trays",
 "downstream ductwork from the VAV box can reach all supply diffusers in the zone without conflicts"],
"Beginners place VAV boxes first and then try to route primary ducts to them. The correct sequence is to route the primary duct first, then position VAV boxes at zone boundaries along the duct.",
"On a floor plan or sketch, draw the primary supply duct route, place two VAV boxes along it, and mark where the ceiling access panels would be.")

w("hvac",76,"Return Air Systems — Ducted vs. Ceiling Plenum",
"Whether return air is collected through dedicated ducts or the ceiling void acting as a plenum fundamentally changes how the ceiling is modeled and what constraints apply to all other services in the void.",
["Ducted return: return air travels back to the AHU through dedicated return ducts — requires significant ceiling void space alongside supply ducts",
 "Ceiling plenum return: the entire ceiling void acts as the return air path — no return ducts modeled but the void must be airtight and combustible material restrictions apply",
 "Plenum-rated requirement: in a ceiling plenum return system, all cables, insulation, and materials in the void must be plenum-rated",
 "Coordination impact: a plenum return system creates material requirements that affect electrical and data teams — this must be flagged early",
 "Confirm the return air method in the project specifications before finalizing HVAC BIM coordination"],
"On a healthcare project, the HVAC engineer specified ducted return for infection control reasons. The initial BIM model only showed supply ducts. When return ducts were added to the already-crowded ceiling void containing beams, sprinklers, cable trays, and lighting, two zones had to be completely redesigned with relocated AHU positions.",
["the return air method (ducted or plenum) is confirmed in project specifications before HVAC coordination is finalized",
 "if ducted return is specified, return duct routing is included in the coordination model alongside supply ducts",
 "if ceiling plenum return is used, the plenum-rated material requirement is flagged to the electrical and data teams"],
"Beginners model only supply systems and assume return air will be resolved later. In ducted return systems, return ductwork can occupy as much ceiling void space as the supply ductwork.",
"Check the HVAC specification (or ask the engineer) whether the project uses ducted return or ceiling plenum return. Write down what changes in your coordination approach for each option.")

w("hvac",77,"Smoke Control and Pressurization Systems in BIM",
"Smoke control systems are required in high-rise buildings, hospitals, and large public spaces. BIM modelers need to understand which HVAC elements belong to the smoke control system to model and coordinate them correctly.",
["Smoke control uses HVAC systems to manage smoke movement during a fire — keeping escape routes clear for occupants",
 "Stairwell pressurization: dedicated fans supply fresh air into stairwells under fire conditions to maintain a smoke-free escape route",
 "Smoke exhaust: large atria, car parks, and retail atriums use dedicated smoke exhaust fans to remove smoke from the space",
 "Smoke control fans must be temperature-rated — typically 200°C for 60 minutes or 400°C for 30 minutes — unlike normal HVAC fans",
 "In Revit: model smoke control ductwork and fans in a separate system type or dedicated workset, distinct from normal HVAC"],
"On a 35-storey residential tower, smoke control fans were initially placed as standard supply fans. During the fire authority review, the temperature rating was queried. The correct rated fans were 300mm wider than the standard fans modeled, requiring the fan room layout to be revised — a change that could have been avoided if the correct families were used from the start.",
["fans designated as smoke control have the correct temperature rating in their Revit parameters",
 "smoke control ductwork is assigned to a separate Revit system type, distinguishable from normal HVAC supply and exhaust",
 "smoke exhaust fans discharge directly to the outside with no shared ductwork connecting to normal HVAC systems"],
"Beginners treat smoke control systems as just another HVAC system. The distinction matters because smoke control equipment has separate standards, testing regimes, and coordination responsibilities.",
"Identify one smoke control component in a building you know or research (stairwell fan, smoke exhaust vent, pressurization AHU). Write down one way it must function differently from a normal HVAC unit.")

w("hvac",78,"HVAC Equipment Submittals and BIM Model Updates",
"BIM models must reflect actual equipment being installed, not just the design engineer's assumed sizes. Submittal review is the process that aligns the BIM model with what will physically arrive on site.",
["Equipment submittals are documents provided by the contractor showing the specific manufacturer and model number proposed for each HVAC item",
 "Common differences between design assumption and submittal: equipment may be larger, have connections on a different face, or require different clearances",
 "BIM modeler's role in submittal review: compare submitted dimensions and connection locations to the model family — update if dimensions differ by more than the agreed tolerance",
 "Key parameters to check: width, depth, height, weight (structural impact), connection face, connection size, access panel requirements, electrical connection point",
 "If submitted equipment does not fit in the modeled space, the contractor must find an alternative or the room layout must be revised — this is resolved in BIM before concrete is poured"],
"On a commercial project, the HVAC contractor submitted a chiller 200mm longer than the design assumption. The BIM coordinator found the extra length would block pipe maintenance access on the non-drive end. The contractor sourced an alternative model with the same capacity but shorter casing — a change that cost nothing during design but would have been expensive after installation.",
["when a submittal is approved, the Revit family dimensions are updated to match the approved equipment dimensions",
 "the connection face and connection size on the approved submittal match the pipes already modeled in the BIM",
 "the weight of the approved equipment is within the structural loading assumed in the structural design"],
"Beginners update the model only after construction begins, when actual equipment arrives. By then, size differences have already caused coordination problems.",
"Find one equipment data sheet online (AHU, FCU, or chiller — any manufacturer). Write down its dimensions and compare them to a typical Revit family for the same equipment type.")

w("hvac",79,"HVAC Model LOD 350 — Required Elements Before Coordination",
"LOD 350 is the coordination standard most projects require before construction. Understanding what LOD 350 means for HVAC ensures the model is complete enough to support clash detection and installation planning.",
["LOD 350 means the model element is accurate enough for trade coordination and prefabrication drawing production",
 "Ductwork at LOD 350: actual cross-section dimensions, insulation thickness as clearance zone, all fittings (elbows, tees, transitions), all accessories (dampers, fire dampers, access doors), connection to equipment",
 "Equipment at LOD 350: outer envelope dimensions match approved submittal, maintenance clearance zones are modeled or documented, all connection points located correctly",
 "Parameters required at LOD 350: duct system type, airflow (CFM or L/s), insulation type and thickness, LOD status, Mark value",
 "Common LOD 350 gaps: missing insulation clearance, generic fittings instead of actual geometry, equipment without maintenance zone, missing fire dampers"],
"On a hospital project, the HVAC model was submitted as 'LOD 350' but insulation clearances were not modeled. When the clash test ran, 87 duct-to-structure clashes appeared — all caused by insulation clearance not being included in the geometry. The model was returned for revision, delaying the coordination package by three weeks.",
["all insulated ducts have insulation thickness added as a clearance zone in the model geometry",
 "all duct fittings are modeled with actual geometry, not represented as straight duct segments",
 "all fire dampers, volume control dampers, and access doors are placed at their correct locations before the model is issued"],
"Beginners model ductwork at LOD 300 (correct route and size) and claim LOD 350 without adding insulation clearance, fittings, or accessories.",
"List the five LOD 350 elements required for one HVAC zone: duct size, insulation, fittings, accessories, and equipment connection.")

w("hvac",80,"HVAC Model Quality — 10-Point Self-Check",
"A model quality self-check before every submission prevents rework, protects your professional reputation, and demonstrates the discipline that senior coordinators recognize and reward.",
["Run this 10-point check before every HVAC model submission:",
 "1. System assignment: every duct and fitting is assigned to the correct Revit MEP system",
 "2. Open connectors: no unconnected duct ends exist — verified with the System Inspector",
 "3. Element naming: all equipment has a Mark value; ducts use the correct type name",
 "4. LOD status: all elements are at the agreed LOD for this submission stage",
 "5. Insulation: applied to all ducts requiring it per the project specification",
 "6. Fire dampers: placed at all fire-rated wall and floor penetrations",
 "7. Clearance: access clearance zones are maintained around all equipment",
 "8. Coordination zone: no elements are placed outside the agreed scope boundary",
 "9. Revit warnings: warning count is below 50 and no critical warnings exist",
 "10. NWC export: a fresh NWC export has been tested in Navisworks before submission"],
"A BIM coordinator who implemented this 10-point check as a team routine saw the average clash count per HVAC submission drop from 340 to 95 within two months. The reduction came from fixing open connector and system assignment errors before submission — errors that had been generating phantom clashes in Navisworks.",
["running the Revit System Inspector shows zero unconnected HVAC elements",
 "all HVAC equipment has a Mark value visible in the element properties",
 "a test NWC export opens correctly in Navisworks with all elements visible in the selection tree"],
"Beginners skip the self-check because it feels like extra work. In practice, an unchecked model returns for revision and costs more time than the check would have taken.",
"Run 3 of the 10 checks on any HVAC model you have access to. Write down what you find for each of the three.")

w("hvac",81,"TAB — Testing, Adjusting, and Balancing — What BIM Supports",
"TAB is the commissioning process that verifies HVAC systems deliver the correct airflow and water flow to every space. BIM models support TAB — but only if the model carries accurate system data.",
["TAB (Testing, Adjusting, and Balancing) is performed after installation to verify airflow and water flow meet design specifications at every terminal",
 "The TAB engineer uses the BIM model's schedule data to understand the design airflow for each supply diffuser, VAV box, and FCU",
 "For BIM to support TAB: every terminal device must have the design airflow in its parameters; all equipment must have correct system assignment",
 "Volume control dampers must be modeled because TAB engineers adjust them during balancing — if they are missing from the model, the TAB report cannot reference them",
 "After TAB: some as-balanced airflows will differ from design — update BIM parameters to reflect actual balanced values if required by the EIR"],
"On an office project, the TAB engineer requested the HVAC airflow schedule from the BIM model before the balancing run. The schedule showed 22 supply diffusers with no airflow value — the families were placed but the CFM parameter was never filled in. The TAB engineer had to use the engineer's paper design schedules instead, working around the BIM model entirely.",
["every supply and return diffuser in the model has a design airflow value (CFM or L/s) in its properties",
 "volume control dampers are modeled at their installed locations and appear in the HVAC schedule export",
 "the HVAC system schedule exported from Revit matches the engineer's design airflow schedule before the TAB run"],
"Beginners model ductwork geometry correctly but rarely fill in flow parameters. The model is geometrically useful but not usable for commissioning or facilities management.",
"Open any HVAC model and check 5 supply diffusers. How many have a design airflow value in their properties?")

w("hvac",82,"HVAC and Structural Coordination — Penetrations and Hangers",
"HVAC ductwork is often the largest element competing for space with structure. Coordinating penetrations and hanger points before concrete is poured is far less expensive than coordinating after.",
["Slab penetrations: where ductwork passes through a concrete slab, a sleeve or opening must be coordinated and submitted before the slab is poured",
 "Submit a penetration schedule: grid reference, elevation, size, fire rating, and discipline for each slab opening",
 "Beam web penetrations: duct passing through a structural steel beam web requires structural engineer approval — location, size, and reinforcing details",
 "Hanger spacing: typically every 2400mm for rectangular ducts under 600mm wide; hanger attachment points must not conflict with structural elements",
 "Combined loading: when HVAC, plumbing, and electrical hang from the same structural bay, check cumulative point loads do not exceed slab capacity"],
"On a hospital project, 47 slab penetration requests were submitted. The structural engineer approved 39, requested repositioning for 6 (too close to column heads), and rejected 2 (penetrations through post-tensioned slab ribs). Reviewing all 47 in the BIM model before drilling began saved an estimated 3 days of post-construction remediation work.",
["every duct crossing a structural slab is submitted as a penetration request with grid reference, elevation, and size",
 "duct hanger attachment points do not coincide with structural beams or slab ribs",
 "beam web penetrations have received structural engineer approval before the duct route is finalized"],
"Beginners model the duct route without considering where physical hangers will attach. In dense ceiling voids, hanger locations become a coordination issue in their own right.",
"For one duct run in a model or sketch, identify two points where trapeze hangers would be required. Note whether each attachment point is clear of the structure.")

w("hvac",83,"HVAC and Ceiling Grid Coordination",
"HVAC supply diffusers and return grilles must align with the architectural ceiling grid. Getting this wrong creates visible misalignment that the client notices immediately — and rework that is expensive to fix after ceiling tiles are installed.",
["Standard ceiling tiles are 600×600mm or 1200×600mm — diffusers must be centered on a tile or span a tile joint cleanly",
 "The ceiling grid is set out from an architectural origin point — confirm with the architect before placing diffusers",
 "Coordination sequence: confirm ceiling grid layout, place HVAC diffusers on the grid, then route ductwork back to the VAV box",
 "Common conflicts: diffuser location coincides with a light fitting, smoke detector, or sprinkler head in the same ceiling zone",
 "The final diffuser layout must match the architectural reflected ceiling plan (RCP) before it is issued to site"],
"On a hotel lobby with a custom ceiling pattern, HVAC diffusers were positioned for optimal airflow without reference to the ceiling tile grid. When the coordinated RCP was issued, 11 diffusers were in the wrong location. Repositioning them required re-routing 8 branch ducts and revising 3 VAV zone boundaries.",
["all supply diffusers are positioned at the center of a ceiling tile or at a defined grid-aligned location",
 "no diffuser location coincides with a light fitting, smoke detector, or sprinkler head in the coordinated ceiling model",
 "the HVAC diffuser layout has been shared with the architectural team for RCP coordination before the ceiling package is issued"],
"Beginners optimize diffuser placement for airflow first and check ceiling grid alignment later. In practice, the ceiling grid is fixed first and HVAC must work within it.",
"Draw a 3×3 grid of 600×600mm ceiling tiles. Place 4 supply diffusers and 1 return grille ensuring they align with tile centers and do not conflict with each other.")

w("hvac",84,"HVAC Commissioning Preparation",
"Commissioning verifies that the installed HVAC system performs as designed. A well-maintained BIM model accelerates commissioning by providing accurate system data and reducing the time the commissioning team spends searching for information.",
["Commissioning engineers need from the HVAC BIM model: equipment list with specifications, airflow schedule by zone and terminal, access point locations for each damper and piece of equipment",
 "Before commissioning: verify all equipment has manufacturer and model number in parameters, all design airflows are assigned to terminals, all access panels are modeled at their locations",
 "Commissioning sequence: ductwork pressure test, damper function test, fan speed verification, airflow measurement at each terminal, system balancing",
 "After commissioning: as-balanced airflows may differ from design — update BIM parameters if the EIR requires as-installed accuracy"],
"On a large office project, the commissioning engineer requested the HVAC airflow schedule 5 days before the TAB run. The model schedule was complete and accurate, allowing the commissioning team to pre-position measurement equipment at each terminal before arriving on site. The TAB run completed in 2 days instead of 4.",
["all HVAC equipment in the model has a Mark value, manufacturer name, and model number in its parameters",
 "a schedule of all supply terminals showing design airflow by zone can be exported directly from Revit",
 "access panel locations are modeled or documented so commissioning teams can reach dampers and equipment without opening ceiling tiles randomly"],
"Beginners think commissioning only involves the installed system, not the model. In practice, the BIM model is the reference document for commissioning planning — an incomplete model slows commissioning.",
"From any HVAC model or project you know, list three pieces of information the commissioning engineer would most need to plan the TAB run.")

w("hvac",85,"HVAC As-Built Requirements",
"After installation, the as-built model must reflect what was actually built — not what was designed. Understanding what changes in the field and why prepares you for the as-built update process.",
["Common as-built changes in HVAC: equipment relocated during installation, duct routes modified at site to avoid unforeseen clashes, access panels added or relocated, duct sizes changed due to late coordination decisions",
 "As-built accuracy levels vary: some EIRs require millimeter-accurate geometry; others require only system-level accuracy (correct connections and parameters)",
 "Most critical as-built data for facilities management: equipment location, connection sizes, valve locations, access panel locations",
 "Update process: site team marks up drawings during construction; BIM modeler updates the Revit model after each zone is completed, not as a batch at the end",
 "LOD 500: as-built models are sometimes described as LOD 500, meaning actual installed conditions are verified and recorded in the model"],
"On a commercial project, the HVAC contractor made 12 routing changes during installation — all approved via RFI but never updated in the BIM model. When the facilities team received the as-built model, 3 fire damper access panels shown in the model were not at their physical installed locations. Ceiling tiles had to be removed in multiple locations to find the actual damper positions.",
["a process exists to record site changes from RFIs and site instructions and update the BIM model accordingly",
 "all approved routing changes are incorporated in the Revit model before the as-built package is issued",
 "access panel locations in the as-built model match their physically installed locations"],
"Beginners treat as-built updates as a batch activity at project end. Updating as changes are approved is far easier than reconstructing what changed after construction is complete.",
"Think of one HVAC change that typically happens on site (a duct re-routed around unexpected structure). Write down what information you would need from the site team to update the model accurately.")

w("hvac",86,"Top 5 Common HVAC BIM Errors",
"Learning from common errors is faster than discovering them on your own project. These five HVAC BIM errors appear repeatedly on real projects and most are completely avoidable.",
["Error 1: Insulation clearance not modeled — duct looks fine but insulation was not included, causing post-coordination clashes",
 "Error 2: Wrong system assignment — duct modeled as exhaust is assigned to supply system, causing incorrect schedule data and missed connections in the system inspector",
 "Error 3: VAV box and diffuser misaligned with ceiling grid — placed for coordination convenience, not aligned to the tile pattern",
 "Error 4: Missing fire dampers — duct passes through fire-rated walls without damper families; only discovered during fire authority review",
 "Error 5: Equipment at design dimensions, not submittal dimensions — AHU or FCU modeled at the engineer's assumed size, not the approved submittal size, causing installation fit problems"],
"A review of 10 HVAC models on commercial and healthcare projects found Error 4 (missing fire dampers) to be the most costly. Fire authority reviews returned models with 20 to 60 missing dampers, each requiring a model revision, coordination review, and drawing re-issue.",
["duct insulation clearance is included as part of the duct geometry for all specified insulated ductwork",
 "every duct in the model is assigned to a named Revit MEP system, visible and correct in the system inspector",
 "fire damper families are placed at every fire-rated boundary penetration before the coordination model is issued"],
"Beginners focus on modeling speed and miss small details like system assignment and insulation. These details take minutes to fix during modeling but hours to correct after coordination is finalized.",
"Review one of the five error types in any HVAC model you have access to. Can you find an example, or confirm it is not present?")

w("hvac",87,"HVAC Coordination Review Checklist",
"A structured pre-submission review reduces rework, demonstrates professional quality, and builds trust with project managers and senior coordinators who review your work.",
["The HVAC coordination review covers six areas: system completeness, geometry accuracy, parameters, trade coordination, documentation, and file hygiene",
 "System completeness: all supply, return, exhaust, and OA systems are modeled; all equipment is connected; all accessories are placed",
 "Geometry accuracy: duct sizes match the engineer's design schedule; equipment dimensions match approved submittals; insulation clearances are included",
 "Parameters: all equipment has Mark values; all ducts have system type; design airflows are entered for all terminals",
 "Trade coordination: a clash test has been run against structure and fire protection; critical clashes are resolved or flagged",
 "File hygiene: Revit warnings are below 50; file is named per the project convention; NWC export tested in Navisworks"],
"On a government building project, introducing a formal coordination checklist that all trades completed before submission reduced HVAC review time from an average of 5 days to 2 days. Common pre-checklist errors — missing system assignments, excessive Revit warnings, wrong file names — were caught before submission rather than during review.",
["the Revit System Inspector shows zero unconnected HVAC elements in the submitted model",
 "a clash test against at least the structural model has been run and the results are available alongside the submission",
 "the submitted NWC file opens in Navisworks and all elements appear correctly in the selection tree"],
"Beginners submit models without a checklist because it feels like extra work. An unchecked model consistently takes longer to review and usually comes back for revision — costing more time than the checklist would have taken.",
"Write your own 5-item HVAC model checklist based on the past 27 days of learning. These should be the five most important checks before any submission.")

w("hvac",88,"HVAC Deep-Dive Wrap-Up",
"Day 88 completes the HVAC discipline deep-dive. This is a moment to consolidate what you have covered, identify what to practice next, and prepare for what real HVAC BIM work looks like in the field.",
["Over the past 28 days you have covered: system flow from AHU to diffuser, duct sizing logic, VAV systems, AHU room layout, fire dampers, condensate drainage, smoke control, submittals, LOD 350, quality checks, commissioning support, and as-built requirements",
 "Key competencies you have built: reading HVAC systems in Revit, identifying coordination conflicts between HVAC and other trades, applying model quality standards, understanding commissioning and as-built processes",
 "What comes next in practice: these concepts are entry-level competencies for an HVAC BIM modeler — the next step is applying them on a real project or a practice model",
 "Areas to keep developing: duct sizing calculations, Navisworks clash grouping, system balancing documentation, and working with MEP engineers on design intent"],
"A junior HVAC BIM modeler who completed a structured 90-day program joined a hospital project team. In the first week, they identified a missing fire damper that the senior coordinator had overlooked during a busy review period. The find was small, but it demonstrated coordination awareness beyond just drawing ducts — and the junior modeler was included in coordination meetings earlier than expected.",
["you can explain what a VAV system is and why VAV boxes require ceiling access panels",
 "you can name the five most common HVAC BIM errors and describe how to check for each one",
 "you can describe what information the commissioning engineer needs from the HVAC BIM model before a TAB run"],
"Beginners sometimes finish a training program feeling they are not ready for real work. The foundation is real. The next step is practice, not more theory.",
"Write 3 sentences: one thing you are confident doing in HVAC BIM, one thing you want to practice more, and one question you would ask a senior HVAC coordinator on your first real project.")

# Day 89 and 90 - final wrap-up days
w("hvac",89,"HVAC Discipline Integration — How HVAC Connects to Other MEP",
"HVAC does not exist in isolation. Understanding how HVAC connects to plumbing, electrical, fire protection, and structure makes you a more complete coordination team member — not just an HVAC specialist.",
["HVAC connects to plumbing: condensate drains, chilled water and heating water connections to AHU and FCU, domestic cold water to humidifiers",
 "HVAC connects to electrical: power supply to AHU, FCU, VAV actuators, pumps; control wiring for BMS points; emergency power for smoke control fans",
 "HVAC connects to fire protection: fire dampers at rated boundaries; sprinkler heads must clear HVAC ducts; smoke detectors in ductwork",
 "HVAC connects to structure: hanger loads, equipment pad footings, slab penetrations for risers and exhaust shafts",
 "In BIM coordination: HVAC is usually the first trade modeled because it requires the most ceiling void space — other trades route around HVAC"],
"On a healthcare project, a junior HVAC modeler flagged that the fire protection team had placed sprinkler heads in locations that conflicted with 4 supply diffusers on the same reflected ceiling plane. The HVAC modeler had coordinated against structure and electrical but had not shared the model with the fire protection team. The issue was resolved with a single coordination meeting that produced 6 revised sprinkler head positions.",
["every chilled water and heating water pipe connection at the AHU is coordinated with the piping team's model",
 "power supply to all HVAC equipment is confirmed with the electrical team's load schedule",
 "fire damper locations have been shared with the fire protection team to confirm no downstream sprinkler conflicts"],
"Beginners coordinate HVAC against structure and sometimes electrical but often miss the connections to plumbing and fire protection until late in the process.",
"List 3 HVAC-to-other-discipline connections on a typical floor: one to plumbing, one to electrical, and one to fire protection. Describe what information must be coordinated for each.")

w("hvac",90,"HVAC Month 3 Complete — Next Steps",
"Day 90 marks the end of the 90-Day MEP BIM Starter Program. You have completed the Foundation curriculum and the HVAC discipline deep-dive. This lesson sets out what to do next.",
["What you have completed: 8 Foundation tracks covering MEP BIM orientation, Revit MEP basics, drawing reading, model quality, clash coordination, data and schedules, site-readiness, and BIM career habits — plus 30 days of HVAC deep-dive",
 "The 90-day program gives you a structured entry point into HVAC BIM coordination work. Real competency develops through project practice — the program is the map, not the destination",
 "Next steps for HVAC BIM practice: find or create a sample Revit MEP model, practice running clash tests against a structural model, practice filling in HVAC schedules with design data",
 "Career development: look for junior MEP BIM modeler or BIM coordinator roles that include HVAC coordination; portfolio projects can include sample models with annotated coordination decisions",
 "Continuing education: the Personal Tutor plan provides personalized daily lessons, level checks, and monthly progress reports for learners who want structured advancement beyond the Starter foundation"],
"A Starter Plan graduate applied for a junior BIM coordinator role. In the interview, they were asked to walk through how they would coordinate an HVAC system with the structural model. Using concepts from the 90-day program — system assignment, LOD 350, clash grouping, penetration submission — they answered confidently. They were offered the role as a junior BIM coordinator with a 6-month probation.",
["you can describe the end-to-end HVAC BIM coordination process from system setup to as-built model",
 "you can identify the three most common coordination clashes between HVAC and other trades and explain how to resolve them",
 "you have a plan for what to practice next to build on the 90-day foundation"],
"Beginners who complete a program sometimes wait for the perfect opportunity to apply their skills. The best practice is to start with a sample model immediately — imperfect application builds competency faster than waiting.",
"Write your next 3 learning actions: one thing to practice in Revit, one model to find or create, and one role or project to work toward in the next 3 months.")

print("\n=== HVAC Complete ===")

# ─────────────────────────────────────────────
# PIPING Days 68-90
# ─────────────────────────────────────────────
piping_lessons = [
(68,"Chilled Water System Overview — Supply, Return, and Flow Direction",
"Chilled water systems are the circulatory system of large HVAC plants. Understanding how water flows from chiller to AHU and back is the foundation for coordinating all piping connections in BIM.",
["The chilled water system uses chilled water produced by a chiller to cool air in AHUs and FCUs",
 "Primary loop: water circulates from chiller evaporator through the primary pumps and back — this loop maintains constant flow through the chiller",
 "Secondary loop: distribution pumps push chilled water through the building to AHUs and FCUs — flow varies based on cooling demand",
 "Supply water is typically 6-7°C; return water is 12-14°C after absorbing heat from the air",
 "In Revit: supply and return pipes must be assigned to separate system types — 'Hydronic Supply' and 'Hydronic Return'",
 "Flow direction determines pipe connection orientation at every piece of equipment — verify supply and return connections match the equipment's inlet/outlet faces"],
"On a commercial tower, the piping modeler connected chilled water supply and return pipes to the AHUs without confirming the connection face orientation in the manufacturer's submittal. Seven AHUs had their supply and return connected in reverse. The error was discovered during commissioning when the water flow meters showed reversed temperature differentials. Correcting the pipe connections required the piping contractor to return to 7 levels.",
["supply and return pipes are assigned to separate named Revit MEP systems throughout the chilled water distribution",
 "the flow direction at each AHU and FCU connection matches the manufacturer's indicated supply inlet and return outlet",
 "a Revit pipe system diagram can be produced showing the complete chilled water flow path from chiller to each AHU"],
"Beginners often model the pipe geometry correctly but reverse supply and return at equipment connections because they did not confirm the connection face in the submittal.",
"Sketch a simple chilled water flow diagram: chiller → primary pump → distribution header → two AHUs → return header → chiller. Label supply temperature (6°C) and return temperature (13°C) at each segment."),

(69,"Pipe Sizing Basics — Velocity, Pressure Drop, and Schedule Reference",
"Pipe sizes in a BIM model must match the engineer's design calculations. Understanding the basic logic behind pipe sizing helps you verify your model against the pipe schedule and identify errors before they reach coordination.",
["Pipe sizing balances two factors: velocity (how fast the water moves) and pressure drop (how much pump energy is required to push it)",
 "Typical velocity limits for chilled water: 1.5-3.0 m/s in distribution mains; 0.5-1.5 m/s in terminal connections to FCUs",
 "Higher velocity = smaller pipe (cheaper) but more noise and higher pressure drop",
 "Lower velocity = larger pipe but quieter and lower energy consumption",
 "The engineer produces a pipe schedule listing each section of the system with its design flow rate and required pipe size",
 "BIM modeler's role: model the pipe at the size shown on the engineer's schedule — do not resize based on visual judgment"],
"On a hospital project, a junior piping modeler resized several branch pipes to 'look right' relative to the main pipe without checking the engineer's schedule. The downsized branches had velocities exceeding 4 m/s — causing pipe noise complaints in occupied wards. The contractor had to replace 40 metres of branch pipework after occupation.",
["every pipe in the BIM model matches the pipe size shown in the engineer's pipe sizing schedule for that section",
 "the main distribution pipe sizes are larger than the branch pipes feeding individual AHUs or FCUs",
 "no pipe size has been changed from the engineer's schedule without a documented design instruction"],
"Beginners resize pipes to maintain visual proportionality in the model rather than following the engineer's sizing schedule. Pipe sizes in BIM must reflect engineering calculations.",
"Request or find a simple pipe sizing schedule from a project or textbook. Pick three pipe sections and verify whether the sizes in the schedule make sense given the flow direction."),

(70,"Pump Room Layout — Arrangement, Discharge Headers, and Isolation",
"The pump room is the heart of the piping system. Getting the equipment arrangement correct in BIM before construction prevents costly structural modifications and ensures maintenance access is preserved.",
["Pump arrangement: in large systems, multiple pumps operate in parallel — each with isolation valves on suction and discharge, a non-return valve on discharge, and a pressure gauge",
 "Suction header: a large-diameter pipe that collects water from the chiller and distributes it to the pump inlets",
 "Discharge header: collects water from all pump outlets and delivers it to the distribution system",
 "Valve placement: isolation valves must be accessible — this drives pump spacing and aisle widths in the model",
 "Clearance: allow 600mm minimum between pump side and wall for valve access; 900mm in front of pump for motor removal"],
"On a commercial project, the pump room layout was modeled with pumps 450mm from the wall — sufficient for pipe connections but not for motor removal during maintenance. Facilities engineers discovered this after occupation when the first pump motor needed replacement. A temporary wall panel had to be cut to allow extraction.",
["each pump has isolation valves on both suction and discharge sides that are reachable without climbing over pipework",
 "non-return valves are modeled on the discharge side of each pump",
 "there is a 900mm clear access corridor in front of each pump for motor and impeller removal"],
"Beginners model pump rooms to fit the equipment on plan without verifying that maintenance access clearances are met. Pump rooms that look clean on screen often fail in practice.",
"Sketch a simple pump room layout with two parallel pumps, suction header, discharge header, isolation valves, and a maintenance aisle. Check that 900mm front clearance exists for each pump."),

(71,"Expansion Tanks and Air Separators in Hydronic Systems",
"Expansion tanks and air separators are small but critical components in hydronic piping systems. Missing or misplaced in the BIM model, they create commissioning failures that are expensive to correct after installation.",
["Expansion tank: absorbs the volume change of water as it heats and cools — prevents excessive pressure fluctuations in the closed loop",
 "Placement: the expansion tank connects to the system at the pump suction — this is the point of zero pressure in the system",
 "Sizing: expansion tank size depends on system volume and operating temperature range — the engineer specifies the size; the BIM modeler places the family correctly",
 "Air separator: removes dissolved air from the water before it can cause noise, corrosion, and reduced heat transfer",
 "Placement: the air separator is installed in the return pipe near the pump suction, upstream of the expansion tank connection",
 "Automatic air vents: small automatic venting devices placed at high points in the system to release trapped air"],
"On a district cooling project, the expansion tank was modeled at the pump discharge instead of the suction side — an error that passed unnoticed through BIM coordination. During commissioning, the system experienced water hammer and pressure surges. The expansion tank had to be relocated, requiring the contractor to cut and re-weld two pipe connections and rerun pressure tests.",
["the expansion tank connects to the system at the pump suction side, not the discharge",
 "an air separator is modeled in the return line upstream of the expansion tank connection point",
 "automatic air vents are placed at the highest points in the distribution system"],
"Beginners often place expansion tanks and air separators wherever they fit spatially without verifying the correct system connection point.",
"In a simple hydronic system sketch, mark the correct positions for: expansion tank, air separator, and two automatic air vents. Label why each position is correct."),

(72,"Isolation Valves, Balancing Valves, and Commissioning Sets",
"Valves are what make a piping system maintainable, adjustable, and commissionable. Every valve in the BIM model must be in the right location, of the right type, and accessible — or the system cannot be operated as designed.",
["Isolation valves: gate or butterfly valves that allow a section of pipe or a piece of equipment to be isolated for maintenance without shutting down the whole system",
 "Balancing valves: manual or automatic valves that set the flow rate through each branch to ensure correct distribution — required at every FCU and terminal unit",
 "Commissioning sets: combined isolation valve and flow measurement device installed at each terminal unit — allow the TAB engineer to measure and set flow during commissioning",
 "Valve placement rule: isolation valves must be reachable without ladders or tools — this affects how much space must be left around pipe risers and horizontal runs",
 "In Revit: model each valve type with its correct family — generic valve families produce incorrect schedule data"],
"On a hotel project, balancing valves were omitted from 34 FCU connections because the BIM modeler assumed they would be added by the contractor. During commissioning, the TAB engineer found that many FCUs were receiving significantly more or less flow than designed because there was no way to balance the branches. Retrofitting commissioning sets after ceiling tiles were installed cost $28,000.",
["isolation valves are placed on both sides of every major piece of equipment",
 "balancing or commissioning valves are placed at every terminal unit (FCU, fan coil, AHU) in the BIM model",
 "all modeled valves use the correct Revit family type corresponding to their function (gate, butterfly, ball, balancing)"],
"Beginners omit valves from BIM models because they are small and add modeling time. Missing valves create commissioning and maintenance problems that are expensive to retrofit.",
"List 5 locations on a chilled water system where isolation valves must be placed and explain why each is necessary."),

(73,"Pipe Insulation — Specification, Clearance, and Coordination",
"Pipe insulation serves multiple purposes: preventing heat gain, preventing condensation, and providing acoustic damping. In BIM, insulation must be modeled as an additional clearance layer — not just noted on a drawing.",
["Chilled water pipes require insulation to prevent condensation and heat gain — typical thickness is 25-50mm depending on pipe size and ambient conditions",
 "Insulation adds to the effective diameter of the pipe — a 100mm pipe with 38mm insulation has an overall diameter of 176mm",
 "In Revit: insulation can be applied to pipes as an additional layer using the pipe insulation parameter — this adds to the model geometry for clash detection",
 "Coordination impact: insulated pipes require more clearance from walls, slabs, structural beams, and other services",
 "Insulation type: for chilled water, typically closed-cell foam (Armaflex or similar) — this differs from the mineral wool used on hot water and steam pipes"],
"On a commercial building, pipe insulation was not modeled in the BIM coordination. After installation, 12 insulated chilled water pipes were found to be touching or pressing against structural beams — creating thermal bridges that caused condensation and dripping. The contractor had to re-route or re-insulate all 12 locations.",
["pipe insulation thickness is applied in the Revit pipe insulation parameter for all chilled water and hot water pipes",
 "insulated pipe diameter (pipe plus insulation) is used for all clash detection runs, not bare pipe diameter",
 "the minimum clearance between insulated pipes and adjacent surfaces meets the specification requirement"],
"Beginners model bare pipe sizes and assume installers will add insulation without coordination. Insulated pipes are significantly larger and require dedicated clearance space in the ceiling void.",
"For one chilled water pipe in a model or sketch, calculate the total installed diameter including insulation. How much more clearance does this require compared to the bare pipe?"),

(74,"Pipe Support and Hanger Coordination",
"Pipe supports and hangers hold the distribution system in place throughout its operating life. BIM modeling of hanger positions and types prevents structural conflicts and ensures the system can be installed and maintained.",
["Pipe hangers attach to the structure above and hold the pipe at its design elevation — the attachment point must be a suitable structural member",
 "Hanger spacing: maximum spacing depends on pipe material and diameter — typically 2400-3000mm for steel pipe, 1200-1800mm for copper",
 "Trapeze hangers: used when multiple pipes run parallel — a horizontal rod carries multiple pipes at different levels from one set of structural attachment points",
 "Hanger point conflicts: attachment bolts or rods cannot pass through post-tensioned slabs, embedded services, or waterproofing membranes",
 "In BIM: model hanger attachment points at the correct spacing and verify each attachment is to an accessible structural element"],
"On a hospital project, the piping team submitted a hanger point schedule showing 340 structural attachment points. The structural engineer identified 18 points that fell within the flat soffit of a post-tensioned slab — attachment was not permitted. The piping team had to re-route 4 pipe runs to find alternative hanger attachment zones.",
["hanger attachment points are spaced at or below the maximum spacing for the pipe material and diameter",
 "no hanger attachment point is located within a post-tensioned slab, waterproofing membrane, or embedded conduit zone",
 "trapeze hanger widths account for all pipes they carry, with minimum 50mm spacing between adjacent pipe insulation"],
"Beginners model pipes without considering where the physical hangers will connect to the structure. In dense ceiling voids, hanger attachment zones become a critical coordination constraint.",
"For one 10-metre pipe run in a model or sketch, mark the hanger positions at the correct spacing. Note which structural elements each hanger would attach to."),

(75,"Flexible Connections and Vibration Isolation",
"Pumps, chillers, and AHUs create vibration that must not be transmitted through the building structure via the piping system. Flexible connections in BIM ensure this requirement is modeled — not just noted in a specification.",
["Flexible connections (also called expansion joints or flexible hose assemblies) are installed at the connection points between rotating equipment and rigid pipe",
 "Purpose: absorb vibration, allow for thermal expansion of pipe, and accommodate minor misalignment during installation",
 "Location: required at suction and discharge of every pump; at connections to chiller evaporator and condenser barrels; at AHU connections on vibration isolation pads",
 "Length: typically 300-500mm on each side of the equipment — the flexible section requires clearance beyond the rigid pipe route",
 "In Revit: model flexible connections as fittings between the equipment connector and the first rigid pipe isolation valve"],
"On a commercial tower, flexible connections were not modeled at pump discharge points — only at the suction side. During commissioning, vibration was measurable through the building structure on all levels served by one pump. A flexible connection was retrofitted at the discharge, but the confined pump room made installation complex and added 3 days to the commissioning program.",
["flexible connections are modeled at both suction and discharge of every pump in the BIM model",
 "flexible connections are also placed at AHU chilled water connections where the AHU is on vibration isolation mounts",
 "the length of the flexible connection section has clearance in the model — it is not compressed against a wall or valve"],
"Beginners model rigid pipe directly from pump connection to isolation valve without allowing space for flexible hose. The omission is discovered during installation when the piping contractor finds no room to install the required component.",
"Identify one pump in a project or sketch. Mark the location of flexible connections on both suction and discharge sides, allowing realistic length for each flexible hose."),

(76,"Flanged, Grooved, and Threaded Connections — When and How",
"Connection types determine installation method, maintenance access requirements, and BIM family selection. Modeling the wrong connection type leads to schedule errors and installation coordination issues.",
["Flanged connections: bolted plate connections — used for equipment connections, valves above 65mm diameter, and anywhere future disassembly is needed; requires space for bolt tightening on all sides",
 "Grooved (Victaulic) connections: a groove is cut in the pipe end and a mechanical coupling clamps over it — fast to install, requires less radial space than flanged but cannot be used in all applications",
 "Threaded (screwed) connections: used for small-bore pipes (typically 50mm and below) — requires thread engagement; used for instrument connections and domestic water",
 "In Revit: select the correct pipe fitting family for each connection type — using a generic elbow for a flanged connection produces wrong dimensions in the model",
 "BIM coordination impact: flanged joints require bolt clearance (typically 100mm radial clearance around the flange face) — this affects spacing in congested areas"],
"On a plant room project, all pipe-to-equipment connections were modeled as generic fittings. When the piping contractor arrived on site, 14 flanged connections at AHU and chiller interfaces did not have sufficient bolt clearance. Three connections required rotating the equipment connection branch, adding 2 days to the plant room installation.",
["flanged connections are modeled with the correct flange dimensions and bolt clearance radius",
 "grooved connections are used only where the pipe material and diameter allow mechanical coupling, per the engineer's specification",
 "no flanged connection is modeled with less than 100mm clearance around the full flange face for bolt tightening"],
"Beginners model all pipe connections with the same generic fitting regardless of connection type. In practice, each connection type has different dimensional requirements that affect coordination.",
"For one pipe-to-pump connection in a sketch, draw the flanged connection correctly showing flange plate, bolt holes, and the 100mm clearance zone required around the flange face."),

(77,"Mechanical Room Quality Check Before Submission",
"The mechanical room is the most complex piping zone on any project. A dedicated quality check before submission prevents the dense pipework from hiding errors that are expensive to find during construction.",
["Mechanical room quality check covers 8 areas: equipment positioning, pipe connections, valve placement, insulation clearance, maintenance access, structural coordination, fire protection, and electrical connections",
 "Equipment positioning: all equipment is positioned with correct maintenance clearances; lift access route is clear for the largest component",
 "Pipe connections: all suction and discharge connections are to the correct face of each piece of equipment; supply and return are not reversed",
 "Valve placement: isolation valves on both sides of every pump; commissioning valves at all terminal connections; no valve handle blocked by an adjacent pipe",
 "Maintenance access: there is a 900mm access corridor in front of each pump; 600mm side access to valve stems",
 "Structural coordination: a penetration schedule has been submitted for all slab penetrations; hanger points are on accessible structural members"],
"On a hospital mechanical room, a quality check before submission identified 9 valve handles that would be blocked by adjacent pipework — the valves were physically modeled but not checked for operability. Relocating the pipes in the model took 4 hours. Relocating them after installation would have required cutting and rewelding 18 pipe joints.",
["all pump connections are verified against the manufacturer's connection face orientation (supply inlet on correct side)",
 "a maintenance access corridor of 900mm exists in front of each pump and 600mm on the valve side of each major component",
 "a penetration schedule has been submitted to the structural engineer for all slab and wall openings"],
"Beginners complete the mechanical room layout and submit without checking whether all valves can actually be operated in their modeled position.",
"Identify the 3 most critical items to check in a mechanical room BIM model before submission and explain why each matters."),

(78,"Piping Coordination with Electrical — Separation Rules",
"Piping and electrical systems share ceiling voids, risers, and plant rooms. Understanding the separation requirements between pipes and electrical equipment prevents safety hazards and coordination failures.",
["Water pipes must not be routed directly above exposed live electrical equipment — including switch rooms, distribution boards, motor control centres, and server rooms",
 "Minimum separation: typically 300mm horizontal separation between water pipes and cable trays or conduits carrying power cables",
 "If pipes must cross above electrical equipment, a drip-proof tray or diverter must be installed below the pipe to catch any leaks",
 "Pipe flanges and joints must not be located above electrical equipment — the risk of leakage at joints is higher than at straight pipe",
 "In BIM: flag any location where a water pipe is within 300mm of a power cable tray or is routed above an electrical room entrance"],
"On a commercial project, a chilled water pipe was routed across the ceiling of a distribution board room — with a flanged joint directly above the main busbars. The electrical engineer flagged the safety issue during the final coordination review. Re-routing the pipe required moving a 6-metre section through a congested ceiling void, adding 3 days to the piping program.",
["no water pipe is routed directly above an exposed live electrical distribution board, MCC, or switch room",
 "horizontal separation between water pipes and power cable trays is at least 300mm or as specified by the project",
 "no pipe flange or mechanical coupling is located within 600mm directly above electrical equipment"],
"Beginners route pipes by the shortest path without checking what is below their route. Routing above electrical equipment creates safety risks that override spatial efficiency.",
"Identify one location in a project or sketch where a pipe route would conflict with the electrical separation rule. Describe an alternative route that maintains the required separation."),

(79,"Piping LOD 350 Requirements",
"LOD 350 is the coordination standard at which pipe models are accurate enough for trade coordination, clash detection, and prefabrication. Understanding the LOD 350 requirements for piping ensures the model is ready before it is issued.",
["Piping at LOD 350 requires: correct pipe diameter (matching engineering schedule), correct pipe material and specification, all fittings (elbows, tees, reducers) as actual geometry not representations, all valves and accessories placed at correct locations, insulation modeled as clearance layer",
 "Equipment at LOD 350: outer dimensions match approved submittal, all pipe connection points located at correct face and elevation, maintenance clearance zones documented",
 "Parameters required at LOD 350: pipe system type, design flow rate, pipe specification (pressure rating, material), insulation specification, LOD status",
 "Common LOD 350 gaps in piping models: missing insulation clearance, pipe reducers missing between different pipe sizes, valve families not matching specified type",
 "Pipe drawings at LOD 350 must be sufficient to produce isometric spool drawings for prefabrication without additional survey"],
"On a laboratory project, the piping model was issued as LOD 350 for coordination but pipe reducers were modeled as symbolic connections rather than actual reducer geometry. The clash detection missed 8 reducer-to-structure conflicts because the model showed straight pipe where a physically larger reducer fitting would be installed. All 8 clashes were discovered during installation.",
["all pipe reducers are modeled with actual reducer fitting geometry, not as a direct size change in the straight pipe",
 "pipe insulation thickness is applied to all specified insulated pipes and included in the clash detection geometry",
 "all valves are modeled with correct Revit families matching their specified type — gate, butterfly, ball, or commissioning valve"],
"Beginners model pipes at the correct diameter throughout but omit fittings and insulation because they are smaller than the pipe. These omissions cause clash detection to miss real installation conflicts.",
"List the five LOD 350 elements required for one section of chilled water piping: pipe diameter, material, fittings, insulation, and valves."),

(80,"Piping Model Quality Self-Check",
"A piping model quality check before every submission catches errors that are cheap to fix in the model and expensive to discover during coordination review or installation.",
["Run this 8-point check before every piping model submission:",
 "1. System assignment: every pipe is assigned to the correct Revit MEP system (Hydronic Supply / Return / Domestic Cold Water etc.)",
 "2. Open connectors: no unconnected pipe ends — check with Revit System Inspector",
 "3. Size transitions: reducers are placed wherever pipe size changes — no direct size jumps in the model",
 "4. Insulation: applied to all pipes requiring it per specification",
 "5. Valve placement: isolation valves at all specified equipment connections; balancing valves at all terminals",
 "6. Slope: drainage pipes and condensate pipes have correct slope — check in elevation view",
 "7. Structural penetrations: all slab and wall penetrations are submitted or flagged",
 "8. Revit warnings: warning count below 50 and no critical warnings"],
"A piping coordinator introduced this 8-point check as a pre-submission standard. Within 6 weeks, the number of clash-detection returns (models sent back for correction rather than proceeding to coordination) dropped from 4 in 10 submissions to 1 in 10. The single biggest improvement came from catching open connectors and missing reducers before the model was issued.",
["the Revit System Inspector shows no unconnected pipe elements in the submitted model",
 "every pipe size change in the model has a reducer fitting — there are no direct diameter jumps",
 "all pipes requiring insulation per the specification have insulation applied in the Revit model"],
"Beginners submit piping models without checking for open connectors and missing reducers because these errors are not visually obvious in a 3D view.",
"Run the 8-point check on any piping model you have access to. Write down the result for each of the 8 checks."),

(81,"Piping Commissioning and Pressure Testing",
"Pressure testing is required before piping systems are insulated and closed in. BIM models support pressure testing by defining system boundaries, test point locations, and documentation.",
["Pressure test: the piping system is filled with water and pressurized to 1.5 times operating pressure for a defined period — typically 4 hours with no pressure drop allowed",
 "System boundary: before pressure testing, the system is sectioned into test zones — isolation valves define zone boundaries",
 "Test points: pressure gauges and temporary blanks are installed at specific points; these locations must be accessible during the test",
 "BIM support: the model can be used to produce system boundary diagrams showing which valves define each test zone",
 "After pressure testing: all results are recorded in a test record; the BIM model is updated if any pipe routes were changed to resolve test failures"],
"On a hospital project, the piping contractor conducted pressure tests on the chilled water system in 6 zones. The BIM model was used to produce the system boundary diagrams that the testing engineer used to locate the correct isolation valves for each zone. Without the model, the testing engineer would have spent an estimated half day per zone identifying valve locations.",
["isolation valves are placed in the BIM model at all logical system boundary points where pressure test zones would be defined",
 "pressure gauge connection points are accessible from a standard step ladder without removal of ceiling tiles or soffit panels",
 "after any pipe route change made to resolve a pressure test failure, the BIM model is updated to reflect the as-tested condition"],
"Beginners do not consider pressure testing during BIM coordination. Pressure test zone boundaries are determined by isolation valve locations — if valves are missing, zones cannot be isolated.",
"Divide a simple chilled water distribution system sketch into 3 pressure test zones. Draw the isolation valves that would define each zone boundary.")

]

for lesson in piping_lessons:
    w("piping", *lesson)

print("\n=== Piping Complete ===")

# ─────────────────────────────────────────────
# PIPING Days 82-90
# ─────────────────────────────────────────────
piping_tail = [
(82,"Piping Coordination with HVAC and Structure",
"Piping systems must be coordinated against HVAC ductwork, structural elements, and other services before construction. In dense ceiling voids, this coordination determines which trade routes first and which trades must adapt.",
["Routing priority in ceiling voids: gravity-fed systems (drainage, condensate) are routed first because they cannot change elevation; HVAC ducts are routed next because they are largest; then piping and cable trays",
 "HVAC to piping coordination: chilled water pipes connecting to AHU must reach the correct connection face without crossing the HVAC supply or return duct route",
 "Structure to piping: all beam web penetrations for pipes require structural engineer approval — pipe size and location must be submitted before structural steelwork is fabricated",
 "Slab penetrations: riser pipes through structural slabs require sleeves to be cast in or cored — submit penetration schedule before concrete is poured",
 "Combined BIM coordination: run clash tests against the structural model, HVAC model, and electrical model before issuing the piping model"],
"On a commercial office project, the piping team routed chilled water mains through three structural beam webs without submitting penetration requests. The structural engineer rejected all three penetrations — the beam webs in those locations contained critical reinforcing. The piping team had to re-route 24 metres of main pipe above the beams, losing 150mm of ceiling void and creating new conflicts with HVAC.",
["all piping beam web penetration requests have been submitted to and approved by the structural engineer before the coordination model is issued",
 "chilled water pipes connecting to AHUs do not cross or block the HVAC supply and return duct main routes",
 "a clash test against the current structural model has been run and all critical clashes are resolved or flagged"],
"Beginners run clash tests against one or two trades and assume the rest will sort out during construction. A coordinated piping model must be checked against structure, HVAC, and electrical before submission.",
"List 3 piping-to-structure coordination actions that must happen before a piping model can be issued for construction."),

(83,"Piping As-Built Requirements",
"As-built piping records are critical for facilities management — valve locations, pipe diameters, and system boundaries must be accurate or maintenance and emergency isolation become guesswork.",
["Common as-built changes in piping: pipe routes modified to avoid late-identified structural conflicts, valve locations adjusted for access, additional isolation valves added, pipe sizes changed due to late engineering revisions",
 "Most critical as-built data for piping: isolation valve locations (for emergency and maintenance isolation), pipe diameters (for flow calculations), pressure test zone boundaries",
 "Update process: record all RFI-approved changes in the BIM model during construction; do not batch-update at project completion",
 "Riser as-built accuracy: riser pipes in vertical shafts are difficult to access after construction — ensure the as-built model records the correct sleeve location and pipe offset from the shaft wall",
 "LOD 500: as-built piping models at LOD 500 are used as the basis for building management system integration and facilities management handover"],
"On a district cooling project, the as-built piping model was issued 6 months after practical completion, reconstructed from marked-up drawings. When a chilled water isolation valve was needed for emergency maintenance 18 months later, the facilities team found that 4 valves shown in the as-built model were at different locations in the ceiling void. The building had to remain partially uncooled for 2 days while valves were located physically.",
["a process is in place to update the BIM model from approved RFIs and site instructions as they occur — not as a batch at the end",
 "isolation valve locations in the as-built model are verified against physical installed positions before the model is handed over",
 "riser pipe locations in shafts are recorded with correct offsets from the shaft walls in the as-built model"],
"Beginners treat as-built updating as a single end-of-project activity. By then, the details of each change have been forgotten and the update is based on incomplete records.",
"Think of one piping change that commonly occurs on site. Write down what information you would need from the site team to update the BIM model accurately."),

(84,"Top 5 Common Piping BIM Errors",
"Learning from errors that appear repeatedly on real projects is more efficient than discovering them for the first time on your own project. These five piping BIM errors are the most frequently found on MEP coordination reviews.",
["Error 1: Supply and return pipes reversed at equipment — the most common and costly piping BIM error; discovered only at commissioning",
 "Error 2: Missing pipe reducers — direct pipe size changes without reducer fittings; causes clash detection to miss the larger fitting footprint",
 "Error 3: Insulation not modeled — pipes clash with structure during installation when insulation is applied; not visible in the uninsulated BIM model",
 "Error 4: Balancing valves omitted — commissioning cannot be completed; retrofitting after ceiling closure is expensive",
 "Error 5: Incorrect system assignment — supply pipes assigned to return system or vice versa; produces wrong data in schedules and system inspector"],
"A piping model review on a commercial project found all five errors present in a single model submission. The model was returned for full revision, adding 8 days to the coordination program. Error 1 (reversed supply/return) and Error 5 (wrong system assignment) appeared together — the modeler had modeled the correct route but assigned the wrong system type, then reversed the connection at the AHU to try to fix the system display.",
["supply and return pipe system assignments are verified at every equipment connection point",
 "reducer fittings are present wherever pipe diameter changes in the model",
 "insulation thickness is applied to all specified insulated pipes before the model is used for clash detection"],
"Beginners often fix the most visible errors (open connectors, Revit warnings) before submission and miss the less visible but more critical errors (reversed supply/return, missing reducers).",
"Review one piping model for all five error types. Write down whether each error is present, absent, or cannot be determined from the information available."),

(85,"Piping Coordination Review Checklist",
"A structured pre-submission piping review demonstrates professional quality and prevents the back-and-forth of unchecked model submissions.",
["The piping coordination review covers 7 areas: system completeness, flow direction, fittings, insulation, valves, trade coordination, and file quality",
 "System completeness: all pipes are connected to equipment or end at a correctly placed cap or open stub; no floating pipe sections",
 "Flow direction: supply and return assignment is correct at every equipment connection; pipe system types in the Revit inspector show a connected network from source to terminal",
 "Fittings: reducers are placed at all size transitions; elbows and tees use actual fitting geometry",
 "Insulation: insulation is applied to all pipes specified to be insulated; insulated diameter is used for clash detection",
 "Valves: isolation valves are on both sides of all major equipment; balancing valves are at all terminal connections",
 "File quality: Revit warnings below 50; NWC export tested and verified in Navisworks"],
"On a large commercial project, the piping contractor implemented a formal pre-submission checklist for all piping zone submissions. Review turnaround time dropped from an average of 7 days to 3 days because the most common errors — reversed connections, missing reducers, and open connectors — were caught before submission.",
["the piping model passes the Revit System Inspector with zero unconnected elements",
 "a clash test against the structural model has been run and reviewed before submission",
 "the submitted NWC file opens correctly in Navisworks with all piping elements visible"],
"Beginners submit models without a checklist because submission deadlines feel more urgent than review quality. Unchecked models consistently require more total review time than checked models.",
"Create your own 5-item piping model checklist based on what you have learned over the past 25 days."),

(86,"Piping Discipline Integration — How Piping Connects to Other MEP",
"Piping does not operate in isolation. Understanding how the piping system connects to HVAC, electrical, plumbing, and fire protection makes you a more complete coordination team member.",
["Piping connects to HVAC: chilled water and heating water pipes connect to AHUs, FCUs, and fan coil units — the connection face and flow direction must be coordinated",
 "Piping connects to electrical: pumps, valves, and control panels require power and BMS connections — pipe routing must allow electrical cable routes to equipment",
 "Piping connects to plumbing: make-up water to the expansion tank and chemical dosing points require domestic water connections from the plumbing system",
 "Piping connects to fire protection: fire suppression systems in plant rooms may be mist or gas suppression — confirm whether water-based sprinklers are also required",
 "Piping connects to structure: all pipe routes through slabs and beams require penetration approval — this must be coordinated before structural work is complete"],
"On a hospital project, the piping and electrical teams coordinated their models separately before federated coordination. When the models were combined, the electrical team's cable tray for pump motor starters ran directly through the space allocated for the pump suction piping. Three weeks of re-coordination were required because neither team had shared their models during their individual design phases.",
["chilled water pipe connections to all AHUs and FCUs are coordinated with the HVAC team before either model is issued for construction",
 "motor control centre locations for pump starters are shown in the piping team's coordination zone",
 "make-up water connections from the plumbing system to the hydronic expansion tanks are included in the piping model"],
"Beginners coordinate piping against structure and then issue the model without confirming connections to electrical and plumbing. Multi-trade coordination requires sharing model data across all disciplines simultaneously.",
"List 3 piping-to-other-discipline connection points on a typical plant room floor and describe the information that must be exchanged for each."),

(87,"Piping Month 3 Coordination Review — Lessons Learned",
"Before completing the piping deep-dive, reviewing the key lessons from the past 4 weeks consolidates your understanding and prepares you to apply these skills on a real project.",
["Week 1 review (Days 61-67): system types, flow direction, pipe sizing logic, pump room layout, expansion tanks, isolation valves, mechanical room quality check",
 "Week 2 review (Days 68-74): chilled water system, pipe sizing, pump rooms, expansion tanks, isolation valves, insulation, hanger coordination",
 "Week 3 review (Days 75-80): flexible connections, connection types, mechanical room quality check, electrical separation, LOD 350, model quality check",
 "Week 4 review (Days 81-87): commissioning, structural coordination, as-built requirements, common errors, coordination review checklist, discipline integration",
 "Key skill gained: you can now describe the end-to-end piping BIM coordination process from system setup to as-built handover"],
"On a commercial project, a junior piping BIM modeler who had completed structured training was paired with a senior coordinator for a mechanical room coordination review. The junior modeler identified 4 of the 6 issues the senior coordinator flagged — a supply/return reversal, a missing reducer, a valve with blocked handle access, and an insulation clearance conflict with a structural bracket. The senior coordinator used the exercise to confirm the junior modeler was ready to lead a zone independently.",
["you can explain what pump room coordination involves and name 3 common errors found in pump room BIM models",
 "you can describe the LOD 350 requirements for a piping system and name 3 common gaps",
 "you can run an 8-point piping model quality check and document the result"],
"Beginners often have knowledge without application practice. The lessons in this deep-dive are most valuable when applied to a sample model — even a simple one.",
"Identify 3 things you learned in the piping deep-dive that surprised you or changed how you thought about piping BIM coordination."),

(88,"Piping Deep-Dive Wrap-Up",
"Day 88 completes the piping discipline deep-dive. This is a moment to consolidate, identify what to practice next, and set direction for continuing development.",
["Over the past 28 days you have covered: chilled water system logic, pipe sizing, pump room layout, expansion tanks, valves, insulation, hanger coordination, flexible connections, connection types, commissioning, structural coordination, as-built requirements, common errors, and coordination review",
 "Key competencies built: reading piping systems in Revit, coordinating piping against structure and other trades, applying model quality standards, understanding commissioning and as-built requirements",
 "What comes next in practice: apply these concepts on a real project or practice model — try to trace an entire chilled water system from chiller to terminal and back",
 "Career awareness: piping BIM modelers who understand system logic — not just geometry — can communicate with mechanical engineers and are trusted with more complex coordination zones",
 "Personal Tutor plan: for learners who want personalized advancement, monthly progress reports, and level-based curriculum to continue beyond the Starter foundation"],
"A Starter Plan graduate applying for a junior piping coordinator role was asked in an interview to describe how they would coordinate a pump room for a 10-storey commercial building. Using the concepts from the piping deep-dive — pump arrangement, isolation valves, flexible connections, hanger coordination, and mechanical room quality check — they gave a structured answer that impressed the interviewer. They received an offer for a 3-month junior coordinator trial.",
["you can explain the end-to-end chilled water system flow from chiller to AHU and back",
 "you can describe the 8-point piping model quality check and why each item matters",
 "you have a plan for what to practice next to build on the 28-day piping deep-dive"],
"Write 3 sentences: one thing you are confident doing in piping BIM, one thing you want to practice more, and one question you would ask a senior piping coordinator on your first real project."),

(89,"Piping Discipline Integration with Plumbing and Fire Protection",
"Piping systems share risers, plant rooms, and ceiling voids with plumbing and fire protection systems. Understanding these overlaps prevents late-stage conflicts and coordination failures.",
["Piping and plumbing share plant rooms: make-up water connections, chemical dosing water, and domestic cold water for drinking fountains in mechanical rooms are all from the plumbing system",
 "Riser coordination: in high-rise buildings, HVAC chilled water risers, domestic water risers, and fire protection risers typically share the same service riser shaft — allocation of space in the shaft is a critical early coordination decision",
 "Fire protection in plant rooms: sprinklers or fire suppression may be installed in mechanical rooms — confirm whether ordinary sprinklers, pre-action sprinklers, or gas suppression are specified before finalizing the plant room layout",
 "Drainage from plant rooms: pump rooms require floor drains connected to the plumbing drainage system — drains must be sized for the full flow from a burst pipe or pressure test failure"],
"On a hospital project, the mechanical plant room had 6 different pipe systems from 4 different contractors sharing the same 8-metre service riser: HVAC chilled water (supply and return), HVAC heating water (supply and return), domestic cold water riser, and fire protection wet riser. Without early riser allocation coordination, two trades would have claimed the same space in the shaft. A riser coordination meeting 3 months before installation resolved the allocation, saving an estimated 4 weeks of rework.",
["the riser shaft allocation plan shows the agreed position for chilled water, heating water, domestic water, and fire risers",
 "floor drains are modeled in the mechanical room and connected to the plumbing drainage system",
 "the fire suppression system type for each plant room is confirmed before finalizing the mechanical room layout"],
"Beginners coordinate HVAC piping against structure and sometimes electrical, but miss the connection points to plumbing and fire protection that are physically inside the same rooms.",
"For one mechanical plant room in a project or sketch, list all the services that would be present and identify two coordination decisions that must be made early to prevent conflicts."),

(90,"Piping Month 3 Complete — Next Steps",
"Day 90 marks the end of the 90-Day MEP BIM Starter Program. You have completed the Foundation curriculum and the Piping discipline deep-dive. This lesson sets out what to do next.",
["What you have completed: 8 Foundation tracks covering MEP BIM orientation through BIM career habits, plus 30 days of piping deep-dive covering chilled water systems, pump rooms, valve coordination, insulation, commissioning, and as-built requirements",
 "The Starter program gives you a structured entry point into piping BIM coordination. Real competency develops through project practice — the program is the map; the work is the destination",
 "Next steps for piping BIM practice: model a simple pump room in Revit, assign correct systems, place isolation and balancing valves, apply insulation, and run a clash test against a structural model",
 "Career development: look for junior MEP BIM modeler or mechanical BIM coordinator roles; piping knowledge combined with HVAC BIM understanding makes you versatile across mechanical coordination",
 "Continuing education: the Personal Tutor plan provides personalized daily lessons and monthly progress reports for learners who want structured advancement"],
"A Starter Plan piping track graduate spent 3 months after the program building a sample Revit MEP model of a pump room layout, complete with chilled water supply and return, pumps, isolation valves, balancing valves, expansion tank, and air separator. They published the model on LinkedIn with a written description of the coordination decisions made. Within 4 weeks, they received 3 responses from MEP BIM companies offering junior roles.",
["you can explain the chilled water system flow from chiller through pumps to AHU and back",
 "you can describe the 5 most common piping BIM errors and how to check for each",
 "you have a plan for what to practice next — a specific model to build or a project to seek out"],
"Write your next 3 learning actions: one Revit model to build, one coordination skill to practice, and one role or project to target in the next 3 months.")
]

for lesson in piping_tail:
    w("piping", *lesson)

print("=== Piping Days 82-90 Complete ===")
print("Script complete.")
PYEOF
